# Generated by Django 2.1 on 2018-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите контент статьи', max_length=3000, verbose_name='Контент')),
                ('pub_date', models.DateTimeField(blank=True, help_text='Дата публикации', null=True, verbose_name='Опубликовано')),
                ('category', models.ManyToManyField(help_text='Выберите категорию статьи', to='firstapp.Category')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
