# Generated by Django 2.1 on 2018-08-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'В наличии'), ('o', 'Читают'), ('a', 'Доступно'), ('r', 'Ожидается')], default='d', help_text='Доступность книги', max_length=1),
        ),
    ]
